name: Mineral Contest
version: v1.1.0
author: ylanouh
main: fr.ylanouh.mineralcontest.Main
commands:
  mc:
    permission: mineralcontest.admin
    description: Commande complète pour la partie (/mc help)